# Generated by Django 6.0.2 on 2026-03-01 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_contactmessage_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, max_length=255, verbose_name='URL страницы')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
            },
        ),
        migrations.CreateModel(
            name='DailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(db_index=True, max_length=255, verbose_name='URL страницы')),
                ('view_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Дневной просмотр',
                'verbose_name_plural': 'Дневные просмотры',
                'unique_together': {('page_url', 'view_date')},
            },
        ),
    ]
